### ISSUE TITLE
Development environment instructions incomplete

### ISSUE THREAD

**Issue by lucaswerkmeister** [danmichaelo/croptool#143]
Here’s a (probably incomplete) list of things I had to do to get a (somewhat) working development environment, beyond what’s described in the “setting up a development environment” section in the README.

- Copy `config.dist.ini` to `config.ini`.
- Run `generate-key.php`.
- Change the tool to run from http://172.28.128.4 rather than an https://tools.wmflabs.org faked via `/etc/hosts`, since Toolforge uses HSTS and modern browsers don’t allow users to override certificate warnings on HSTS-protected sites.
  - Update the `hostname` in `config.ini`.
  - Update the OAuth callback URL in `src/php/App.php`.
  - Change cookie-related function calls in `src/php/App.php` and `src/php/Session.php` to no longer require the cookie to be secure (change `true, true` to `false, true`).
- Request an OAuth consumer (for http://172.28.128.4/croptool/, not https://tools.wmflabs.org/croptool/) and add the consumer key and secret to `config.ini`.
- After every code change, run `node_modules/.bin/gulp build && vagrant reload` to make sure the changes are applied (without the `vagrant reload`, I would sometimes get stale files in the browser).

**Comment by lucaswerkmeister** [comment]
Oh, and I also edited `src/index.html` to change all the protocol-relative URLs (`//tools-static.…`) to HTTPS ones (`https://tools-static.…`), to avoid silly NoScript issues like this:

![Screenshot from 2019-12-22 14-55-03](https://user-images.githubusercontent.com/2346599/71322726-15261600-24cb-11ea-8184-8a30b5be624f.png)

**Comment by danmichaelo** [comment]
Thanks for writing this up! The last bullet point reminds me of the many headaches Vagrant have caused me, and Virtualbox is also generally quite slow to work with. Since it's due time to modernize the Vagrant setup in any case (replace trusty with something like Debian stretch), perhaps I should just as well move to Docker. Will look into that first, then update the README. Since changing the hostname is now required, I will also see if I can reduce the number of places where you have to change it.

**Comment by lucaswerkmeister** [comment]
> And since changing the hostname is now required, I will also see if I can reduce the number of places where you have to change it (ideally it would only be in the config.ini file or similar)

That would be great, yeah.

> perhaps I should just as well move to Docker.

For what it’s worth, I can’t use Docker, since I use cgroups v2 on all my systems and Docker still doesn’t support that (though apparently it’s getting close). But maybe I don’t need anything virtualized at all, and Caddy or some other local web server would work just as well for my – I didn’t spend much time investigating that.

**Comment by danmichaelo** [comment]
Interesting, didn't know about cgroups v2, but yes, seems like full support is not far away: https://medium.com/nttlabs/cgroup-v2-596d035be4d7

A virtual environment is included to avoid having to install PHP, ImageMagick, JpegTran and NodeJs (if you run gulp inside the virtual machine, that is...). Originally, the idea was also to have a virtualenv that matched the <s>Tool Labs</s> ToolForge environment as closely as possible with respect to both OS, PHP version etc, but now I've forgotten to update it in some years :)

**Comment by danmichaelo** [comment]
Today my Virtualbox+Vagrant setup broke again, and I couldn't figure out why, so I decided to take the step and move to Docker. The new setup is based on localhost rather than a fake toolforge certificate. I've updated the [instructions in the README file](https://github.com/danmichaelo/croptool#setting-up-a-development-environment), which I think should be complete now.

**Comment by lucaswerkmeister** [comment]
Okay, thanks!
