### ISSUE TITLE
Mark derivatives when subimage is extracted

### ISSUE THREAD

**Issue by owcz** [danmichaelo/croptool#71]
The tool marks new files as {{extracted from}} the original. It follows that the original should be marked that {{Derivative versions}} now exist (either by that template or in the information template's "other_versions" field.

**Comment by danmichaelo** [comment]
I guess the reason i haven't added this before is that it's a little bit more complicated. If a `{{Derivative versions}}` template already exists, the new file must be appended to that. Otherwise a new template must be added. And template parsing can be quite messy.

But I've put together an implementation now that hopefully will add or update the template in a sane way in most cases:

- If a {{Derivative versions}} template already exists, add the filename
  to it.
- If not, add the template to the `other_versions` field if found,
  otherwise try adding it above the license-header, above the first
  category or just at the end of the text.

Let me know if you have ideas for improvement. Note that the code is not yet deployed since I'm currently waiting for #73 to be approved.

**Comment by owcz** [comment]
That all sounds good to me

**Comment by danmichaelo** [comment]
Seems like it works: https://commons.wikimedia.org/w/index.php?title=File%3ASele%C3%A7%C3%A3o_alem%C3%A3_de_futebol_feminino_faz_primeiro_treino_em_Bras%C3%ADlia_%2828242338583%29.jpg&type=revision&diff=203561712&oldid=203560867

The thumbnail is perhaps a little large. I'll reduce it somewhat.

**Comment by owcz** [comment]
Nice! Should the cropped image's `{{Extracted from}}` also be put in its `| other_versions=` field?

**Comment by danmichaelo** [comment]
Probably a good idea, I changed that.
